import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import NavBar from "./components/layout/navbar";
import { ThemeProvider } from "./context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // https://huggingface.co/naver/DUSt3R_ViTLarge_BaseDecoder_512_dpt  model image to 3d
  title: "HW3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
          <ThemeProvider>
          <AuthProvider>
            <NavBar/>
            {children}
            </AuthProvider>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
